### ISSUE TITLE
init-pants should not require a pants.ci.toml

### ISSUE THREAD

**Issue by benjyw** [pantsbuild/actions#11]
Currently that is its default value for the `pants-ci-config` key, and it fails if that file doesn't exist.

We should probably allow that file to not to exist? At least if it wasn't explicitly set (do actions allow us to detect whether it was set explicitly?)

**Comment by benjyw** [comment]
@cognifloyd thoughts?

**Comment by cognifloyd** [comment]
Hmm. Good point.
We can add a workout step that processes the default. It could still use `pants.ci.toml` if it exists and fall back to `pants.toml`.

**Comment by Eric-Arellano** [comment]
+1 to your proposal @cognifloyd

**Comment by cognifloyd** [comment]
What do you think of #13?
I haven't tested it yet, but that's what I think will work.
