### ISSUE TITLE
lmdb cache is never hit due to incorrect restore key

### ISSUE THREAD

**Issue by CJTurpie** [pantsbuild/actions#12]
In the init-pants action the lmdb cache key can never be hit due to a typo in the key/restore keys.

The cache key (https://github.com/pantsbuild/actions/blob/5f8f24e91fe30b2535a3af9761723ef8ff086e0c/init-pants/action.yaml#L97) is:
- `pants-lmdb-store-${{ runner.os }}-pants-${{ inputs.gha-cache-key }}-${{ github.sha }}`

whilst the restore keys are:
- `pants-lmdb-store-${{ runner.os }}-${{ inputs.gha-cache-key }}-${{ steps.pants-cache-commit.outputs.CACHECOMMIT }}`
- `pants-lmdb-store-${{ runner.os }}-${{ inputs.gha-cache-key }}-`

As you can see the key has an extra `pants` in the middle of the key that the restore keys do not. I suggest removing this from the cache key so that the lmdb cache can be hit.

**Comment by benjyw** [comment]
Ooof, that is a silly bug. Thanks for the report! Would you be open to sending a PR to fix it? (by removing that useless `pants-` bit).

**Comment by benjyw** [comment]
Thanks for the bug report @CJTurpie !
